//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_iCareAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentMetadata()
        {
            this.ModificationHistory = new HashSet<ModificationHistory>();
        }
    
        public System.Guid DocumentID { get; set; }
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int PatientID { get; set; }
        public int UserID { get; set; }
    
        public virtual iCareUser iCareUser { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModificationHistory> ModificationHistory { get; set; }
    }
}
