//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_iCareAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Group3_iCARECBEntities1 : DbContext
    {
        public Group3_iCARECBEntities1()
            : base("name=Group3_iCARECBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<iCareAdmin> iCareAdmin { get; set; }
        public virtual DbSet<iCareUser> iCareUser { get; set; }
        public virtual DbSet<iCareWorker> iCareWorker { get; set; }
        public virtual DbSet<UserPassword> UserPassword { get; set; }
    }
}
