//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_iCareAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentRecord
    {
        public int AssignmentID { get; set; }
        public int UserID { get; set; }
        public int PatientID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
    
        public virtual PatientRecord PatientRecord { get; set; }
    }
}
